import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import DefaultLayout from "../../layouts/Default";

type CardProps = {
  name: string;
  phone: string;
  email: string;
  image: {
    url: string;
    alt: string;
  };
  id: number;
  isFavourite: boolean;
  description: string;
};
export default function Home() {
  const router = useRouter();

  const { id } = router.query;

  const [cat, setCat] = useState<CardProps>();

  const fetchCat = async () => {
    const response = await fetch(`/api/cats/${id}`);
    const data = await response.json();
    setCat(data);
  };

  useEffect(() => {
    fetchCat();
  }, []);

  return (
    <div>
      <Head>
        <title>{id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        {cat && (
          <div className="container mt-5" style={{ display: "flex" }}>
            <img src={cat.image.url} />
            <div className="mx-5">
              <h1>{cat.name}</h1>
              <p>{cat.description} </p>
            </div>
          </div>
        )}
      </DefaultLayout>
    </div>
  );
}
